rconfig:
  container_name: rconfig
  image: wtghcivica/rconfig:3.9.6
  #image: local/rconfig
  privileged: true
  restart: always

# To persist data for the web and database configurations, uncomment the 3 lines below:
  volumes:
  - 'mysql:/var/lib/mysql'
  - 'rconfig:/home/rconfig'
  ports:
  - "8080:80"
  - "8443:443"
